server:
  port: 8090
spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/dbgirl
      username: root
      password: meiwenjun
      druid:
        initial-size: 1
        min-idle: 1
        max-active: 20
        test-on-borrow: true
swagger:
  enable: true